server:
  port: 8888
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    max-connections: 20000

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://112.50.194.163:3306/returnable_robot?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE&useSSL=false&allowMultiQueries=true
    username: root
    password: XMlianluoyimysql123!!!
    ###################???druid?????###########################
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      # ???????????
      initial-size: 10
      min-idle: 50
      max-active: 100
      # ?????????????
      max-wait: 60000
      # ???????????????????????????????
      time-between-eviction-runs-millis: 60000
      # ??????????????????????
      min-evictable-idle-time-millis: 3000000
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      # ??PSCache??????????PSCache???
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters:
        - stat
        - wall
        - log4j
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true

  redis:
    host: 192.168.8.93
    port: 30034
    password: XMlianluoyiredis!!!
    database: 0
    timeout: 30000
    jedis:
      pool:
        max-active: 600
        max-idle: 50
        max-wait: 3000ms
        min-idle: 10
    session:
      timeout: 14400s
      store-type: redis
jedis:
   pool:
    maxIdle: 8
    minIdle: 2
    maxWait: 3000
    maxTotal: 100
    maxInstruction: 2000

## 线程池
thread-pool:
  pool:
    corePoolSize: 10
    maxPoolSize: 20
    keepAliveSeconds: 600
    queueCapacity: 25
  schedule:
    poolSize: 2

#队列配置生产消费者分离
mq:
  activemq:
    isopen: true
    consumer:
      brokerURL: tcp://192.168.8.93:30485
      password: admin
      userName: XMlianluoyimq!!!
    producer:
      brokerURL: tcp://192.168.8.93:30485
      password: admin
      userName: XMlianluoyimq!!!
  rabbitmq:
    isopen: false
    consumer:
      addresses: ${rmq.consumer.addresses}
      userName: ${rmq.consumer.userName}
      password: ${rmq.consumer.password}
      virtualHost: ${rmq.consumer.vhost}
    producer:
      addresses: ${rmq.producer.addresses}
      userName: ${rmq.producer.userName}
      password: ${rmq.producer.password}
      virtualHost: ${rmq.producer.vhost}

mybatis:
  mapper-locations: classpath:/mappings/*.xml
  configuration:
    cache-enabled: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: true
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: true
    auto-mapping-behavior: partial
    default-executor-type: simple
    map-underscore-to-camel-case: true
    local-cache-scope: session
    jdbc-type-for-null: null

# xxl-job配置项
xxl:
  job:
    accessToken: ''
    admin:
      addresses: http://192.168.8.93:32191
    executor:
      appname: returnable-robot
      ip:
      logpath: D:\xxl-job\xxl-job2.1.1
      logretentiondays: -1
      port: 10005


disruptor:
  customerNumList:
    - 10

# 微信支付调用包
cert_path: /data/cert
#cert_path: E:\wechat-new\ReturnableRobot\src\main\resources\file

#日志输出配置
logging:
  level:
    cn.xmlly.chat: Debug #输出INFO级日志，在调试时可调整为DEBUG
  path: logs/
  file:
    max-size: 10MB #每个文件最大为10MB，超过会自动分包
    max-history: 7 #日志最大保存7天
  pattern:
    console: '[%d{yyyy-MM-dd HH:mm:ss.SSS}][%level] [%thread] %logger{60} [%file:%line] %msg%n'
    dateformat: yyyy-MM-dd-HH-mm.SSS
    file: '[%d{yyyy-MM-dd HH:mm:ss.SSS}][%level] [%thread] %logger{60} [%file:%line] %msg%n'